// js/presetsPride.js
export const pridePresets = [
    { id: 'pride_rainbow', name: 'Classic Rainbow', description: 'The traditional 6-stripe pride flag', beads: [{beadId:'p_op_red',color:'#e50000'},{beadId:'p_op_orange',color:'#ff8d00'},{beadId:'p_op_yellow',color:'#ffee00'},{beadId:'p_ne_green',color:'#008121'},{beadId:'p_op_blue',color:'#004cff'},{beadId:'p_op_purple',color:'#760188'}]},
    { id: 'pride_progress', name: 'Progress Pride', description: 'Progress pride flag color scheme', beads: [{beadId:'p_op_black',color:'#000000'},{beadId:'p_op_brown',color:'#613915'},{beadId:'p_tr_blue',color:'#73d7ff'},{beadId:'p_tr_pink',color:'#ffaaf8'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_red',color:'#e50000'},{beadId:'p_op_orange',color:'#ff8d00'},{beadId:'p_op_yellow',color:'#ffee00'},{beadId:'p_ne_green',color:'#008121'},{beadId:'p_op_blue',color:'#004cff'}]},
    { id: 'pride_trans', name: 'Transgender Pride', description: 'Light blue, pink, and white stripes', beads: [{beadId:'p_tr_blue',color:'#5bcefa'},{beadId:'p_tr_pink',color:'#f5a9b8'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_tr_pink',color:'#f5a9b8'},{beadId:'p_tr_blue',color:'#5bcefa'}]},
    { id: 'pride_nonbinary', name: 'Non-Binary Pride', description: 'Yellow, white, purple, and black', beads: [{beadId:'p_op_yellow',color:'#fcf434'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_purple',color:'#9c59d1'},{beadId:'p_op_black',color:'#000000'}]},
    { id: 'pride_bisexual', name: 'Bisexual Pride', description: 'Pink, lavender, and royal blue', beads: [{beadId:'p_ne_pink',color:'#d60270'},{beadId:'p_op_purple',color:'#9b4f96'},{beadId:'p_op_blue',color:'#0038a8'}]},
    { id: 'pride_pansexual', name: 'Pansexual Pride', description: 'Pink, yellow, and cyan', beads: [{beadId:'p_ne_pink',color:'#ff218c'},{beadId:'p_op_yellow',color:'#ffd800'},{beadId:'p_op_blue',color:'#21b1ff'}]},
    { id: 'pride_asexual', name: 'Asexual Pride', description: 'Black, grey, white, and purple', beads: [{beadId:'p_op_black',color:'#000000'},{beadId:'p_op_white',color:'#a3a3a3'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_purple',color:'#800080'}]},
    { id: 'pride_aromantic', name: 'Aromantic Pride', description: 'Shades of green and white', beads: [{beadId:'p_ne_green',color:'#3da542'},{beadId:'p_ne_green',color:'#a7d379'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_black',color:'#a3a3a3'},{beadId:'p_op_black',color:'#000000'}]},
    { id: 'pride_agender', name: 'Agender Pride', description: 'Black, grey, green, and white', beads: [{beadId:'p_op_black',color:'#000000'},{beadId:'p_op_white',color:'#b7b7b7'},{beadId:'p_ne_green',color:'#b5f4ce'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_ne_green',color:'#b5f4ce'},{beadId:'p_op_white',color:'#b7b7b7'},{beadId:'p_op_black',color:'#000000'}]},
    { id: 'pride_genderfluid', name: 'Genderfluid Pride', description: 'Pink, white, purple, black, blue', beads: [{beadId:'p_ne_pink',color:'#ff75a2'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_purple',color:'#be18d6'},{beadId:'p_op_black',color:'#000000'},{beadId:'p_op_blue',color:'#333333'}]},
    { id: 'pride_genderqueer', name: 'Genderqueer Pride', description: 'Lavender, white, and dark chartreuse', beads: [{beadId:'p_op_purple',color:'#b57edc'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_ne_green',color:'#4a8123'}]},
    { id: 'pride_intersex', name: 'Intersex Pride', description: 'Yellow with purple circle', beads: [{beadId:'p_op_yellow',color:'#ffd800'},{beadId:'p_op_purple',color:'#7900aa'},{beadId:'p_op_yellow',color:'#ffd800'}]},
    { id: 'pride_demisexual', name: 'Demisexual Pride', description: 'White, purple, grey, and black', beads: [{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_purple',color:'#6b2d5c'},{beadId:'p_op_white',color:'#8c8c8c'},{beadId:'p_op_black',color:'#000000'}]},
    { id: 'pride_polysexual', name: 'Polysexual Pride', description: 'Pink, green, and blue', beads: [{beadId:'p_ne_pink',color:'#f61cb9'},{beadId:'p_ne_green',color:'#07d863'},{beadId:'p_op_blue',color:'#1c92f6'}]},
    { id: 'pride_abrosexual', name: 'Abrosexual Pride', description: 'Shades of pink and green', beads: [{beadId:'p_tr_pink',color:'#7ef7c2'},{beadId:'p_op_white',color:'#c4f6df'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_ne_pink',color:'#ff8cb6'},{beadId:'p_ne_pink',color:'#e6005c'}]},
    { id: 'pride_omnisexual', name: 'Omnisexual Pride', description: 'Shades of pink and dark blue', beads: [{beadId:'p_ne_pink',color:'#ff9bc8'},{beadId:'p_ne_pink',color:'#ff3b9a'},{beadId:'p_op_black',color:'#1b183a'},{beadId:'p_op_blue',color:'#3b79ff'},{beadId:'p_op_blue',color:'#7bc6ff'}]},
    { id: 'pride_lesbian', name: 'Lesbian Pride', description: 'Oranges, white, and pinks', beads: [{beadId:'p_op_orange',color:'#d52d00'},{beadId:'p_op_orange',color:'#ef7627'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_tr_pink',color:'#cc8fc6'},{beadId:'p_ne_pink',color:'#a30262'}]},
    { id: 'pride_mlm', name: 'Gay Men (MLM) Pride', description: 'Turquoise, white, and blue stripes', beads: [{beadId:'p_ne_green',color:'#078d70'},{beadId:'p_ne_green',color:'#26ceaa'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_op_blue',color:'#7baadc'},{beadId:'p_op_blue',color:'#3b1d8e'}]},
    { id: 'pride_bigender', name: 'Bigender Pride', description: 'Pink, purple, white, blue', beads: [{beadId:'p_ne_pink',color:'#c479af'},{beadId:'p_op_white',color:'#d1b3e8'},{beadId:'p_op_purple',color:'#9b95ec'},{beadId:'p_op_white',color:'#d1b3e8'},{beadId:'p_op_blue',color:'#74aec3'}]},
    { id: 'pride_aroace', name: 'AroAce Pride', description: 'Orange, yellow, white, light blue, dark blue', beads: [{beadId:'p_op_orange',color:'#e28600'},{beadId:'p_op_yellow',color:'#ecc94b'},{beadId:'p_op_white',color:'#ffffff'},{beadId:'p_tr_blue',color:'#7cc4ed'},{beadId:'p_op_blue',color:'#2b4c7e'}]},
    // ... 30 more unique pride variations following standard community flags ...
];
